
package com.cetiti.dsp.filter.soapclient.airquality;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AirQuality", targetNamespace = "http://AirQuality.dsp.cetiti.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AirQuality {


    /**
     * 
     * @param stationCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "stationAirQuality", targetNamespace = "http://AirQuality.dsp.cetiti.com", className = "com.cetiti.dsp.filter.soapclient.airquality.StationAirQuality")
    @ResponseWrapper(localName = "stationAirQualityResponse", targetNamespace = "http://AirQuality.dsp.cetiti.com", className = "com.cetiti.dsp.filter.soapclient.airquality.StationAirQualityResponse")
    @Action(input = "http://AirQuality.dsp.cetiti.com/AirQuality/stationAirQualityRequest", output = "http://AirQuality.dsp.cetiti.com/AirQuality/stationAirQualityResponse")
    public String stationAirQuality(
        @WebParam(name = "stationCode", targetNamespace = "")
        String stationCode);

}
