
package com.cetiti.dsp.filter.soapclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Mapper", targetNamespace = "http://Mapper.dsp.cetiti.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Mapper {


    /**
     * 
     * @param sqlpop
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectErrorCodeWithDsql", targetNamespace = "http://Mapper.dsp.cetiti.com", className = "com.cetiti.dsp.filter.soapclient.SelectErrorCodeWithDsql")
    @ResponseWrapper(localName = "selectErrorCodeWithDsqlResponse", targetNamespace = "http://Mapper.dsp.cetiti.com", className = "com.cetiti.dsp.filter.soapclient.SelectErrorCodeWithDsqlResponse")
    @Action(input = "http://Mapper.dsp.cetiti.com/Mapper/selectErrorCodeWithDsqlRequest", output = "http://Mapper.dsp.cetiti.com/Mapper/selectErrorCodeWithDsqlResponse")
    public String selectErrorCodeWithDsql(
        @WebParam(name = "sqlpop", targetNamespace = "")
        String sqlpop);

    /**
     * 
     * @param levelname
     * @param levelid
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectLevelsWithParams", targetNamespace = "http://Mapper.dsp.cetiti.com", className = "com.cetiti.dsp.filter.soapclient.SelectLevelsWithParams")
    @ResponseWrapper(localName = "selectLevelsWithParamsResponse", targetNamespace = "http://Mapper.dsp.cetiti.com", className = "com.cetiti.dsp.filter.soapclient.SelectLevelsWithParamsResponse")
    @Action(input = "http://Mapper.dsp.cetiti.com/Mapper/selectLevelsWithParamsRequest", output = "http://Mapper.dsp.cetiti.com/Mapper/selectLevelsWithParamsResponse")
    public String selectLevelsWithParams(
        @WebParam(name = "levelid", targetNamespace = "")
        String levelid,
        @WebParam(name = "levelname", targetNamespace = "")
        String levelname);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectStrategys", targetNamespace = "http://Mapper.dsp.cetiti.com", className = "com.cetiti.dsp.filter.soapclient.SelectStrategys")
    @ResponseWrapper(localName = "selectStrategysResponse", targetNamespace = "http://Mapper.dsp.cetiti.com", className = "com.cetiti.dsp.filter.soapclient.SelectStrategysResponse")
    @Action(input = "http://Mapper.dsp.cetiti.com/Mapper/selectStrategysRequest", output = "http://Mapper.dsp.cetiti.com/Mapper/selectStrategysResponse")
    public String selectStrategys();

    /**
     * 
     * @param sql
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectTableWithDsql", targetNamespace = "http://Mapper.dsp.cetiti.com", className = "com.cetiti.dsp.filter.soapclient.SelectTableWithDsql")
    @ResponseWrapper(localName = "selectTableWithDsqlResponse", targetNamespace = "http://Mapper.dsp.cetiti.com", className = "com.cetiti.dsp.filter.soapclient.SelectTableWithDsqlResponse")
    @Action(input = "http://Mapper.dsp.cetiti.com/Mapper/selectTableWithDsqlRequest", output = "http://Mapper.dsp.cetiti.com/Mapper/selectTableWithDsqlResponse")
    public String selectTableWithDsql(
        @WebParam(name = "sql", targetNamespace = "")
        String sql);

}
