
package com.cetiti.dsp.filter.soapclient.airquality;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AirQualityService", targetNamespace = "http://AirQuality.dsp.cetiti.com", wsdlLocation = "http://10.70.7.72:8081/com.cetiti.dsp/AirQuality?wsdl")
public class AirQualityService
    extends Service
{

    private final static URL AIRQUALITYSERVICE_WSDL_LOCATION;
    private final static WebServiceException AIRQUALITYSERVICE_EXCEPTION;
    private final static QName AIRQUALITYSERVICE_QNAME = new QName("http://AirQuality.dsp.cetiti.com", "AirQualityService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.70.7.72:8081/com.cetiti.dsp/AirQuality?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AIRQUALITYSERVICE_WSDL_LOCATION = url;
        AIRQUALITYSERVICE_EXCEPTION = e;
    }

    public AirQualityService() {
        super(__getWsdlLocation(), AIRQUALITYSERVICE_QNAME);
    }

    public AirQualityService(WebServiceFeature... features) {
        super(__getWsdlLocation(), AIRQUALITYSERVICE_QNAME, features);
    }

    public AirQualityService(URL wsdlLocation) {
        super(wsdlLocation, AIRQUALITYSERVICE_QNAME);
    }

    public AirQualityService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AIRQUALITYSERVICE_QNAME, features);
    }

    public AirQualityService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AirQualityService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AirQuality
     */
    @WebEndpoint(name = "AirQualityPort")
    public AirQuality getAirQualityPort() {
        return super.getPort(new QName("http://AirQuality.dsp.cetiti.com", "AirQualityPort"), AirQuality.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AirQuality
     */
    @WebEndpoint(name = "AirQualityPort")
    public AirQuality getAirQualityPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://AirQuality.dsp.cetiti.com", "AirQualityPort"), AirQuality.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AIRQUALITYSERVICE_EXCEPTION!= null) {
            throw AIRQUALITYSERVICE_EXCEPTION;
        }
        return AIRQUALITYSERVICE_WSDL_LOCATION;
    }

}
